(define (plan explore-solution)
  (:problem explore)
  (:steps (teleport-from-ship zoe ship surface)
          (make-peace zoe lizard surface)
          (begin-erupt surface)
          (attack lizard zoe surface)
          (stun zoe lizard)
          (non-executed (kill lizard zoe))
          (teleport-to-ship zoe surface ship)
          (erupt surface)))